FROM openjdk:17 AS build
#Copiar el código fuente y archivos de compilación a la imagen
COPY src /build/src
COPY pom.xml /build
COPY mvnw /build
COPY .mvn /build/.mvn

#Compilar el código
WORKDIR /build
RUN ./mvnw package

#Segunda etapa: no necesita dependencias, solo Java y el .jar
FROM eclipse-temurin:17-jre-jammy AS final
COPY --from=build /build/target/*.jar /app/
WORKDIR /app
EXPOSE 8080

ENTRYPOINT [ "sh", "-c" ]
CMD ["exec java -jar -Dspring.profiles.active=docker /app/*.jar"]
